### ISSUE TITLE
add Rust(std::option::Option) <-> Java(X) mapping

### ISSUE THREAD

**Issue by Dushistov** [Dushistov/rust_swig#11]
Option for Android is hard, so should be setting to generate our own option.

**Comment by VMatrix1900** [comment]
Has this feature been implemented? Can we close this issue?

**Comment by Dushistov** [comment]
@VMatrix1900 

Is is partly implemented, now only `Option<f64 | i64>` handled,
I plan to have implementation for at least `Option<bool | i8 | i16 | i32>` plus `Option<ForeignClass>` before closing this issue.

**Comment by VMatrix1900** [comment]
@Dushistov When will this implemented? In 0.2.1? `Option<ForeignClass>` is very nice to have.

**Comment by Dushistov** [comment]
@VMatrix1900 

Ok, I will include implementation into the next release.

**Comment by coltfred** [comment]
@Dushistov Have you had a chance to start on this at all? I also need this support and was trying to figure out if I should try and write it in a mappings file or not. (Disclaimer: I don't actually know what I'm doing)

**Comment by Dushistov** [comment]
@coltfred 

> Have you had a chance to start on this at all?

As new mantainer, now I am busy with new release of https://github.com/Dushistov/bluetooth-serial-port .
When it will be done, and nobody implement this feature, 

For this feature I imagine to implement something like this:

```Rust
static_method f(x: Option<Foo>) -> Option<Boo>;
```

to

```Java
Optional<T> f(@Nullable Foo x);
```

**Comment by coltfred** [comment]
I haven't, yet. If you're able to do it I could do a code review of it.
That might be very instructive to me.

**Comment by Dushistov** [comment]
Missed things:

1. Support of `Option<i32>` as input/output
2.  i8,i16,f32 as input
3. Option<&str> as input
4. Option<Foreign class> as input

**Comment by coltfred** [comment]
@Dushistov It seems we also don't have Option<String> or Option<&str> as a return type. Did you miss that in your above comment or am I missing something?

**Comment by Dushistov** [comment]
@coltfred 

> It seems we also don't have Option<String> or Option<&str> as a return type. Did you miss that in your > above comment or am I missing something?

I am today did some java job, and missed `Option<&str>` as input argument,
that's why I included it into list. If you need also  `Option<String>`,  `Option<&str>` we
can also include them into list.

**Comment by coltfred** [comment]
I need them as return types. I won't have time to work on this for a few
days so any help you could give would be awesome.

**Comment by Dushistov** [comment]
Missed things:

1.  Support of Option<i32> as input/output
2.   i8,i16,f32 as input
3.  Option<&str> as input
4.  Option<&T> as input
