### ISSUE TITLE
Support Option as value of Result?

### ISSUE THREAD

**Issue by joprice** [Dushistov/rust_swig#133]
I assumed the generation here worked for any supported value type, but checking out the code, it seems to be handled case by case. Is there a reason Option is not supported? As a workaround, I think I can use a better error type and have missing data be one error case.

error: Do not know conversation from such rust type 'Result<Option<DictEntry>, String>' to foreign

**Comment by joprice** [comment]
Seems that I can't use an enum on the right side of a Result either. Is that supported?

**Comment by Dushistov** [comment]
@joprice 

For what language you try generate bindings C++ or Java?

**Comment by joprice** [comment]
Currently C++ since I’m using it from iOS but might try java later as well.

**Comment by Dushistov** [comment]
Then, answering your questions:

>I assumed the generation here worked for any supported value type, but checking out the code, it >seems to be handled case by case. Is there a reason Option is not supported? 

The main feature that I want implement in `rust_swig 1.0` is the way to describe
conversation rules from Rust types <-> Language X types via [DSL](https://en.wikipedia.org/wiki/Domain-specific_language). This is partly implemented, for C++ you can look at predefined rules [here](https://github.com/Dushistov/rust_swig/blob/master/macroslib/src/cpp/cpp-include.rs).
But current DSL variant has flaws, it very limited support of generic  `Language X types`,
it supports generic conversation between rust types, but not for output type in `Language X`

So you can describe rule `Option<T> -> #[repr(C)] union COptionUnion { x: T, is_some: u8 }`, 
and rule for `Result<T, E> ->  #[repr(C)] union CResultUnion {x: T, e: E, is_ok: u8, };`,
but it doesn't yet combine this rules, and doesn't yet automatically generate output C types.

Plus DSL have no yet mechanism to describe C -> C++ conversation, for example conversation rule: 
`union COptionUnion { T x; uint8_t is_some; } -> boost::optional<T>`. 

All parts that doesn't supported yet by DSL I have to hardcoded into `rust_swig` code.
So at now supported only `Result<ForeignClassA, ForeignClassB or String>`,
`Result<(), String or ForeignClassB>`, `Result<Vec<ForeignClass>, String>`.

There are three way how you overcome this restriction:

1. Fix rust_swig
2. Use `foreigner_class` to wrap around result type and error type,
   for example in my current project I do it like this:
```Rust
foreigner_class!(class HttpClientApiError {
    self_type HttpClientApiError;
    constructor HttpClientApiError::default() -> HttpClientApiError;
    private method client_api_ext::error_type(&self) -> u8;
    method HttpClientApiError::to_string(&self) -> String;
    foreigner_code r#"
public:
    enum class Type : uint8_t {
        NetworkError = 0,
        ServerClientApiError = 1,
        AuthFailedError = 2,
        InvalidUrlError = 3,
        InternalError = 4,
        NoAuthAttempt = 5,
    };
    Type type() const noexcept
    {
        return static_cast<Type>(error_type());
    }
"#;
});

foreigner_class!(class HttpClientApiImpl {
    self_type HttpClientApi;
    private constructor = empty;
    static_method HttpClientApi::new(basic_url: &str, rsync_bin_path: &Path) ->
        Result<HttpClientApi, HttpClientApiError>; alias create;
    method HttpClientApi::login(&self, user: &str, pass: &str) ->
        Result<(), HttpClientApiError>;
});
```
Where `HttpClientApiError` is rust enum that implements `std::error::Error` trait.

3. Use DSL, for example in `build.rs` you can write:
```Rust
     let swig_gen = rust_swig::Generator::new(LanguageConfig::CppConfig(
        CppConfig::new(generated_include_dir.clone(), namespace.into()).use_boost(),
    )).merge_type_map("swig-type-map", include_str!("src/swig-type-map.rs"));
```

and in `src/swig-type-map.rs`
```
mod swig_foreign_types_map {
    #![swig_foreigner_type = "struct CResultOptionString"]
    #![swig_rust_type = "CResultOptionString"]
}

impl SwigInto<Result<Option<X>, String>> for CResultOptionString {
    fn swig_into(self) -> CResultOptionString {
        ...
    }
}
```

In fact in cases 1 and 3 almost you wil write almost the same code,
but in case of 1, you can also promote `C struct` CResultOptionString to something like `std::variant<std::optional<X>, RustString>`, to make it more convenient to work with in C++ language.

**Comment by joprice** [comment]
That makes sense. Is there a way to have different code for java and c++ for case 2?

**Comment by Dushistov** [comment]
> Is there a way to have different code for java and c++ for case 2?

Actually the opposite is difficult - use the same code for java and c++,
for example for java/jni, `SwigInto` looks like:
```Rust
trait SwigInto<T> {
    fn swig_into(self, env: *mut JNIEnv) -> T;
}
```
while for `c++`:
```Rust
trait SwigInto<T> {
    fn swig_into(self) -> T;
}
```
As you can see, `Java/JNI` requires additional `JNIEnv` argument.

So, in theory, to reuse the same code you need to call `rust_swig` code twice, and use different files as output if you want to build the same `.so/.dll` library for `C++` and `Java` at the same time.
And each call time you need to provide a different argument for `merge_type_map`.

Personally I use two entrance crates in the workspace, one for c++ and one for java because with `C++` I can use almost the same semantics (copy/move),
while with `Java` sometimes it is much more complex, so some times I have to move rust self_type to `Rc<RefCell<Foo>>`, or even to `Arc<Mutex<Foo>>` to make my API more Java like.

**Comment by Dushistov** [comment]
With current master, for C++ case it is possible to handle any combinations of Result/Option.

Like this one:

```
static_method TestResult::f_res_opt(var: u32) -> Result<Option<Foo>, String>;
```

or even something like this:
```
static_method TestResult::f_res_opt(var: u32) -> Result<Option<Option<Foo>>, Option<String>>;
```
