### ISSUE TITLE
`build.rs` as a library

### ISSUE THREAD

**Issue by rubdos** [Dushistov/rust_swig#141]
> rust_swig is designed to be used from cargo build scripts. Just copy an appropriate code from examples crates: general java, android/java, c++ and add rust_swig as [build-dependencies] into your Cargo.toml.

I don't really like the idea of copy-pasting 250 lines of code. Would it be interesting to, for example, have `gen_for_android()` inside the `rust_swig` library? I think it would be nice to have a (initially opinionated) "default" implementation that can simply be called.

**Comment by Dushistov** [comment]
Hi, @rubdos! 

Thank you for idea.
Actually, `android-example/build.rs` contains only 20-30 lines of code related to`rust_swig`.
All other code related to usage of android ndk+bindgen. And this is very specific code, in some cases
you may want just use `jni-sys` crate and remove all `bindgen` usage, in some cases you have to use `bindgen`. So I am not sure that so specific case and mostly related to other crate `bindget` is worth to integrate with `rust_swig`.

**Comment by Dushistov** [comment]
I made simplification of android-example,
now build.rs as simple as possible:

https://github.com/Dushistov/rust_swig/blob/master/android-example/build.rs

it is now possible swap jni-sys and bindgen generated code without any efforts.
