### ISSUE TITLE
Thread-safe callbacks

### ISSUE THREAD

**Issue by rubdos** [Dushistov/rust_swig#145]
I would like to implement an interface in Java that can be send to Rust in a thread safe way: I basically want to guarantee `Send` on the sent object `Box<MyTraitInterface + Send>`. Is this somehow possible?

Mind that it's late on my day and my brain is getting laggy. I have no idea whether it's somehow possible to do.

**Comment by Dushistov** [comment]
In the hypothetical case - if rust_swig would accept such syntax:

```Rust
foreign_interface!(interface MyObserver {
    self_type OnEvent + Send;
    onStateChanged = OnEvent::something_change(&self, x: i32, s: &str);
});
```
all would be work fine.

All other parts are ready. In one of my projects I use java + Rust (tokio), 
and my callbacks to java comes from thread created by Rust.
So generated code by rust_swig has all necessary code to inform JVM about new thread and so on things.

But I haven't yet use type checking for Rust+Java border,
so at now you have to use `unsafe` in this case to convert `Box<Foo>` to `Box<Foo+Send>`.
