### ISSUE TITLE
Java/feature: handle Vec<ForeignClass> as input param

### ISSUE THREAD

**Issue by rubdos** [Dushistov/rust_swig#146]
#139 for Java. I cannot seem to export methods like

```rust
method foo(&mut self, Vec<Foo>);
```

where `Foo` has been declared before.

**Comment by Dushistov** [comment]
But, if you need just create array of object in Java, and pass them to Rust,
you can write:

```Rust
foreigner_class!(class Foo {
    self_type Foo;
    constructor Foo::new(_: i32) -> Foo;
    method Foo::f(&self, _: i32, _: i32) -> i32;
});

foreigner_class!(class VecFoo {
    self_type Vec<Foo>;
    constructor Vec::new() -> Vec<Foo>;
    method Vec::push(&mut self, _: Foo);
});

foreigner_class!(class Boo {
    self_type Boo;

    constructor Boo::new(_: i32, _: usize) -> Result<Boo, String>;
    method foo(&mut self, _: Vec<Foo>);
});
```

not tested, but should works.

**Comment by rubdos** [comment]
> But it is necessary to allocate memory for each function call with such type as input, because of `jobjectArray` and `Vec<Foo>` is completly different objects, so it is required to create `Vec<Foo>` every time.

I honestly think that allocating is unavoidable anyhow. There are two semantics you can give when passing an Array from Java to Rust. One is to *move* from Java to Rust, the other is to *copy*. The former is the Rusty way, the latter the Java way. The former should invalidate the Java object, but that will be very weird for the callee. The latter seems more appropriate for the callee, but that always requires `T: Clone`.

It's different is the `&[T]` case of course, where things become *way* more complicated...

I am trying to solve the `Vec<T> where T: Clone` case.

**Comment by rubdos** [comment]
I've added this (unfinished) `SwigInto` implementation:

```rust

#[swig_from_foreigner_hint = "T []"]
impl<T: SwigForeignClass + Clone> SwigInto<Vec<T>>  for jobjectArray {
    fn swig_into(self, env: *mut JNIEnv) -> Vec<T> {
        let class_id = <T>::jni_class_name();
        let jcls: jclass = unsafe { (**env).FindClass.unwrap()(env, class_id) };
        let field_id = swig_c_str!("mNativeObj");
        let type_id = swig_c_str!("J");
        let field_id: jfieldID = unsafe { (**env).GetFieldID.unwrap()(env, jcls, field_id, type_id) };
        assert!(!field_id.is_null());

        let length = unsafe { (**env).GetArrayLength.unwrap()(env, self) };
        // pub GetObjectArrayElement: Option<unsafe extern "system" fn(_: *mut JNIEnv, _: jobjectArray, _: jsize) -> jobject>,

        let result = Vec::with_capacity(length as usize);

        for i in 0..length {
            let obj = unsafe { (**env).GetObjectArrayElement.unwrap()(env, self, i) };
        }

        result
    }
}
```

to `jni-include.rs`. The generated Rust (extern C) code looks correct:

```rust
#[allow(non_snake_case, unused_variables, unused_mut)]
#[no_mangle]
pub extern "C" fn Java_com_example_rust_TestContainers_do_1set_1struct_1vec(env:
                                                                                *mut JNIEnv,
                                                                            _:
                                                                                jclass,
                                                                            this:
                                                                                jlong,
                                                                            a_0:
                                                                                jobjectArray)
 -> () {
    let mut a_0: Vec<Foo> = a_0.swig_into(env);
    let this: &mut TestContainers =
        unsafe { jlong_to_pointer::<TestContainers>(this).as_mut().unwrap() };
    let mut ret: () = TestContainers::set_struct_vec(this, a_0);
    ret
}
```

but the generated Java code:

```java
    public final void set_struct_vec(TestPathAndResult [] a0)  {

        do_set_struct_vec(mNativeObj, a0);
    }
    private static native void do_set_struct_vec(long me, TestPathAndResult [] a0) ;
```

selects the wrong type! (`TestPathAndResult []`) instead of `Foo []`. FYI, the tested foreign code:

```rust
foreigner_class!(class TestContainers {
    self_type TestContainers;
    constructor TestContainers::default() -> TestContainers;
    method TestContainers::get_struct_vec(&self) -> Vec<Foo>;
    method TestContainers::get_empty_struct_vec(&self) -> Vec<Xyz>;
    method TestContainers::get_string_vec(&self) -> Vec<String>;
    method TestContainers::set_struct_vec(&mut self, _: Vec<Foo>);
});
```

Would you have any clue where I should teach `rust_swig` to infer the right generic `T`? It seem to just take the first `T: SwigForeignClass` that it knows to map to Java.

**Comment by Dushistov** [comment]
@rubdos 

Looks like I forgot to implement `#[swig_from_foreigner_hint = "T []"]` , only swig_**to**_foreigner_hint is really used inside `rust_swig`, `swig_from_foreigner_hint` just parsed and that's all. I will solve this problem this weekend. Sorry for that.

**Comment by rubdos** [comment]
Great! Do you want me to drop the above code in a pull request? Less work for you then.

**Comment by Dushistov** [comment]
> Do you want me to drop the above code in a pull request? Less work for you then.

You mean completed implementation of `impl<T: SwigForeignClass + Clone> SwigInto<Vec<T>>  for jobjectArray {`? If so - yes, even not optimized version is better then nothing, I suppose.
