### ISSUE TITLE
make_standalone_toolchain.py script is no longer needed for interfacing with arbitrary build systems.

### ISSUE THREAD

**Issue by In-line** [Dushistov/rust_swig#157]
> As of NDK r19, the toolchains installed by default with the NDK may be used in-place. The make_standalone_toolchain.py script is no longer needed for interfacing with arbitrary build systems.

https://developer.android.com/ndk/guides/other_build_systems

**Comment by Dushistov** [comment]
Thanks, android-example doesn't use/require make_standalone_toolchain.py anymore and documentation describes usage of clang based toolchain:

https://dushistov.github.io/rust_swig/java-android-example.html
