### ISSUE TITLE
Optional inputs throw exception on reuse in java.

### ISSUE THREAD

**Issue by coltfred** [Dushistov/rust_swig#168]
The way the optional input code works today takes ownership of the value and causes that object to be unusable in java after it's been passed to the JNI layer.

For instance [this](https://github.com/Dushistov/rust_swig/compare/master...coltfred:test_reuse_optional) causes a panic with the message:
```
[Dynamic-linking native method com.example.rust.TestOptional.do_f4 ... JNI]                    
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21      
```

Our original implementation worked because it required Clone, but since we've moved to the more generic `unbox_object`, it's not working.

**Comment by Dushistov** [comment]
@coltfred 

> The way the optional input code works today takes ownership of the value and causes that object to be 
> unusable in java after it's been passed to the JNI layer.

It is intentional behaviour. The same thing happens for example with:

```Rust
method f(_: Foo);
```

```Java
Foo foo = new Foo;
obj.f(foo);
```

`Clone` may be heavy operation, so I thing it should be explicit:
```Java
//Java
obj.f(foo.clone());
```
not hidden underneath inside generated code.

C++ part supports `#[derive(Copy)]` foreign classes,
I suppose we should call `Clone` only for them implicitly in Java part too.

Plus the last, not implemented part of  #11 is support of `Option<&T>`,
passing objects to functions with such signature should not cause "stealing" of ownership.

**Comment by coltfred** [comment]
@Dushistov You're right that Option<&T> is what I'm actually after. I got used to the Cloning behavior because that's what I was working with in my code before, but this is the correct behavior.

In the case of foreign classes, you can't actually clone them easily so it's all a bit of a pain. (Unless I'm just ill informed, which is possible as I'm no JNI or Java expert). I'll close this issue.

**Comment by Dushistov** [comment]
@coltfred 

>In the case of foreign classes, you can't actually clone them easily so it's all a bit of a pain

You mean CPU time or programmer time?

For the second case, in my project (C++ + Rust case) I have many classes,
for each I export `clone`, for example:

```Rust
foreigner_class!(class Waypoint {
    self_type Waypoint; 
    private constructor Waypoint::default() -> Waypoint;
    method Waypoint::id(&self) -> &str;
    method Waypoint::name(&self) -> &str;
...
    method Waypoint::clone(&self) -> Waypoint;
});
```

If this doesn't work for Java this is bug.

**Comment by coltfred** [comment]
@Dushistov That does work. I was trying to work only in java for the clone, but this will get me by until we can get Option<&T> written. I was going to write issues for the remaining Option work so we could have a more detailed list than referring back to the long history in #11. Is that ok with you? Alternatively I could write a final comment on #11 that details what's left and leave it open.

**Comment by Dushistov** [comment]
@coltfred 

I suppose #11 is enough, no need one more issue.

The problem with `Option<&T>` that 

```Rust
impl<T: SwigForeignClass> SwigFrom<jlong> for Option<T> {
impl<T: SwigForeignClass> SwigFrom<jlong> for Option<&T> {
```

are conflicting implementations, because of E0119 , it is obviously possible deal with this concrete case,
but I want invent some kind of generic solution.
