### ISSUE TITLE
Compilation error in non-MSVC compilers in circular dependent classes

### ISSUE THREAD

**Issue by AdamRzepka** [Dushistov/rust_swig#177]
During #170 I've been using MSVC to test bigger, real world example and it worked OK. However,now I see GCC and clang refuse to compile generated headers (rightfully). Let's say we have:

```rust
struct A {}
impl A {
    fn a(b: &B){}
}

struct B {}
impl B {
    fn b(a: &A){}
}
```

Now, in `A.hpp` we have method `A::a` (and corresponding `B::b in B.hpp`):
```c++
    template<bool OWN_DATA>
    inline bool A<OWN_DATA>::a(const B & a_0) const  noexcept
    {
        A_a(this->self_, static_cast<const BOpaque *>(a_0));
    }
```

`main.cpp` in C++ client app:
```c++
typedef struct BOpaque BOpaque;
#include "c_A.h"
#include "c_B.h"
#include "B_fwd.hpp"
#include "A.hpp"
#include "B.hpp"
// the rest of the file is unimportand
...
```

During compilation of `main.cpp` clang complains:
```
A.hpp: cannot cast from type
      'const B' to pointer type 'const BOpaque *'
```
The error is caused by the fact, that during `A.hpp` parsing, compiler doesn't yet know about user defined conversion from `B` to `BOpaque`, which is defined in B.hpp.
If I reverse the order of includes, the problem will show up in method `B::b`.

The easy fix is to place all methods' implementations in separate A_impl.hpp and B_impl.hpp files, and include them like this:
```
typedef struct BOpaque BOpaque;
#include "c_A.h"
#include "c_B.h"
#include "B_fwd.hpp"
#include "A.hpp"
#include "B.hpp"
#include "A_impl.hpp"
#include "B_impl.hpp"
```

However, this worsens the "include hell" problem (#175) and is not desirable in most cases. It will be ideal, if we provide some option, to split the includes for particular class. Some ideas of solution:

1. Attribute in foreign_class:
```rust
foreigner_class!(
    #[derive(Copy)] 
    #[split_hpp] // name for the attribute is not ideal
    class A {
        self_type A;
        constructor A::new() -> A;
        method agent_handle::id(&self) -> Uuid;
        static_method A::a(&self, &B) ;
    }
);
```
2. Configuration option in `CppConfig` for all classes,
3. Configuration option in `CppConfig` for a particular type,
4. New  attribute in `swig_foreign_types_map`?

I think, the second solution is simplest and sufficient for now.

@Dushistov let me know, if any of these solutions is acceptable for you (or if you have better one) and I can implement it.

**Comment by Dushistov** [comment]
@AdamRzepka 

I don't see any possibility except "split include file into 2 or may be 3 includes",
but final solution I suppose should be 

5. Automatically detect such cases and generated such "A.hpp" and "B.hpp"
   that user can safely include and do not care about details.

To fix #175 we need find out all dependencies of each `foreigner_class!`, so it is possible detect
circular dependencies and do proper things for this case.

So if you need the solution right here and right now, I agree and accept PR that 

> Configuration option in CppConfig for all classes,

after properly fixing #175 I suppose we can deprecate this option,
or just drop it if it happens in the current release cycle.
