### ISSUE TITLE
preserve arguments name if possible

### ISSUE THREAD

**Issue by Dushistov** [Dushistov/rust_swig#181]
It would be nice if code generator could preserve names during processing code like this:

```Rust
method Foo::foo(&self, param: Param);
```

Now in generated code there is "a0" with type `Param`.
It would be nice if in generated code there would be an argument with the name `param` instead of `a0`.

**Comment by ecumene** [comment]
Has there been any work on this yet? If not, I'm going to make a PR and work on it

**Comment by Dushistov** [comment]
> Has there been any work on this yet?

As I know - nobody.

It would be nice if basis of "preserve name functionality"  will be somewhere in `impl ForeignerMethod` (
https://github.com/Dushistov/rust_swig/blob/6301d0d9ddb72a20f9c280cfb9ff04bd5bc5aabb/macroslib/src/types.rs#L80 ), so it would be possible to use it in target language independent way.

**Comment by ecumene** [comment]
This could be solved by something similar to what CBindGen does, take a look at this function

https://github.com/eqrion/cbindgen/blob/b718662520b83a08c341eba27406198d946020dd/src/bindgen/cdecl.rs#L63
