### ISSUE TITLE
Make a simple but complete example

### ISSUE THREAD

**Issue by yjiangnan** [Dushistov/rust_swig#196]
This project seems interesting. However, I am unable to follow what should be done to use it. From the README.md file, all I get is that it is possible to write somewhere some code to use it. But exactly where should I write? Although there is a c++ example, but the example is too complicated and it is unclear how to follow. Which files should I use, modify, or incorporate into my project? Are all the so many files necessary? Do I need to read through all the source code to use it?? 

What would be best is to use a simple example to guide the users through all the steps to use it, for example see [this](https://blog.jonharrington.org/rust-and-swig/). 

Additionally, the README.md file mixes C++ and Java usages together. This only adds to confusions and it should not be required for the users to know all of C++ and Java and Rust to understand what you are talking about. I would suggest separating the C++ and Java explanations into two separate files, each with more clear explanations of what exactly should be done.

**Comment by Dushistov** [comment]
> But exactly where should I write? Although there is a c++ example, but the example is too complicated and it is unclear how to follow. Which files should I use, modify, or incorporate into my project? Are all the so many files necessary? Do I need to read through all the source code to use it??

Yes, it would be nice to have howto, because of c++_tests and jni_tests are primarily tests
and only then examples.

> Integration of rust_swig with your project
> rust_swig is designed to be used from cargo build scripts

So, to use this project in your crate to cooperate with C++ you need
build.rs from c++_tests - 38 lines of code, 
src/lib.rs - 2 lines of code
src/cpp_glue.rs - 3 lines of code.
empty src/cpp_glue.rs.in - 0 lines of code,
all code from src/cpp_glue.rs.in is useless for you as is,
and just example how to describe C++ classes.

**Comment by yjiangnan** [comment]
@Dushistov Thanks for the reply. 
One thing is still unclear. Where do I write the wrapper code? The example has the code in file `cpp_glue.rs.in`. However, is that file ever been imported? I am new to Rust. But my impression is that Rust follows what Python does to explicitly specify the module/file to import. I see nowhere file name "cpp_glue.rs.in" appears.

**Comment by Dushistov** [comment]
> Where do I write the wrapper code? 

in `src/cpp_glue.rs.in`

> However, is that file ever been imported?

No, `src/cpp_glue.rs.in` is not used directly.
In `build.rs` you can find:
```
    rust_swig_expand(
        Path::new("src/cpp_glue.rs.in"),
        &Path::new(&out_dir).join("cpp_glue.rs"),
    );
```
and in `src/cpp_glue.rs` you can see
```Rust
 include!(concat!(env!("OUT_DIR"), "/cpp_glue.rs"));
```

This is common pattern for code generation, you can find detailed description in Cargo's book:

https://doc.rust-lang.org/cargo/reference/build-scripts.html

**Comment by Dushistov** [comment]
Project now contains simplified cpp-example and detailed explanation how it works:

https://dushistov.github.io/rust_swig/getting-started.html
https://dushistov.github.io/rust_swig/cpp-example.html
