### ISSUE TITLE
Unresolved reference when accessing struct fields 

### ISSUE THREAD

**Issue by imerkle** [Dushistov/rust_swig#247]
Is there any way to access struct fields ?

Rust

```
struct A{
data: String,
}

```

Kotlin

```
var a = A()
println(a.data) //unresolved reference: data


```

**Comment by Dushistov** [comment]
@imerkle 

you need getter:

```
struct A{
  data: String,
}

foreigner_class!(class A {
  self_type A;
  fn getData(&self) -> &str {
    &this.data
  }
});
```

**Comment by xajik** [comment]
Hey, maybe there is already some option to generate getter/setter automatically? Or to expose public struct members?

**Comment by Dushistov** [comment]
> Hey, maybe there is already some option to generate getter/setter automatically?

There are a lot of crates for this. So I leave it out of scope of this project.
I personally used:
https://github.com/Hoverbear/getset
https://github.com/yangby-cryptape/rust-property
