### ISSUE TITLE
Put System.loadLibrary in autogenerated Session.java 

### ISSUE THREAD

**Issue by inferrna** [Dushistov/rust_swig#253]
Once we already have java class as a wrapper, why not to load library right inside it? I just tried it and it's working.

```java
public final class Session {

    static {
        try {
            System.loadLibrary("mobcore");
        } catch (UnsatisfiedLinkError e) {
            Log.e("Session", "Load libary ERROR: " + e);
        }
    }

    public Session()  {
...
```

**Comment by Dushistov** [comment]
> Once we already have java class as a wrapper, why not to load library right inside it?

@inferrna , not sure what do you mean. If you mean automatically generate:
```Java
try {
            System.loadLibrary("mobcore");
        } catch (UnsatisfiedLinkError e) {
            Log.e("Session", "Load libary ERROR: " + e);
        }
```
then it is impossible for several reasons:

1. Name of library is unknown: "mobcore" is placed in Cargo.toml, rust_swig doesn't parse any .toml files.
2. You can generate as many of classes  as you want, if each of them use `loadLibary` then it would be overhead, if one of them, then which one?
3. `Log.e` is Android specific, depend on context you want use different methods to handle error,
    note that `rust_swig` is not Android specific it supports "big" Java also.

Obviously 1-3 may be solved by some kind of preferences for `rust_swig::JavaConfig`,
but is any reason to use N lines of Rust code to generated N / 2 lines of Java code,
why not just write Java Code?

And actually you can add any Java code to generated classes:

```
foreigner_class!(class Session {
    self_type Session;
    constructor Session::new() -> Session;
    fn Session::add_and1(&self, val: i32) -> i32;
    fn Session::greet(to: &str) -> String;
    foreigner_code r#"
static {
       anything
    }
"#;
});
```
and in generated code you will see `static { anything }`.

**Comment by Dushistov** [comment]
Fill free to reopen if you have comments about my comments :)
