### ISSUE TITLE
Improve android example

### ISSUE THREAD

**Issue by inferrna** [Dushistov/rust_swig#254]
1. More detailed describe build.rs file. There is variables that **must** be changed before use: at least INCLUDE_SYS_H: and ANDROID_PACKAGE_ID:
2. Add example function taking and returning arrays. I already found myself that if I want
```java
int [] test_arr(int[] values)
```
in Java, then I must 
```rust
fn test_arr(&self, values: &[i32]) -> Vec<i32>
```
in Rust. But that wasn't so obvious.
3. Describe ```*glue*``` files

**Comment by Dushistov** [comment]
> Add example function taking and returning arrays

you can find a lot of examples here: https://github.com/Dushistov/rust_swig/blob/master/jni_tests/src/java_glue.rs.in

**Comment by Dushistov** [comment]
> More detailed describe build.rs file. There is variables that must be changed before use: at least 
> INCLUDE_SYS_H: and ANDROID_PACKAGE_ID:

I made simplification of android-example and no need for these any more

> Describe *glue* files

I added documentation about general idea and android in particular:

https://dushistov.github.io/rust_swig/getting-started.html
https://dushistov.github.io/rust_swig/java-android-example.html
