### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for long [...] init()

### ISSUE THREAD

**Issue by arrtchiu** [Dushistov/rust_swig#265]
Looking for some guidance - I've most likely done something wrong. For whatever reason it seems the jni methods aren't getting generated or included into my .so file. Upon instantiating a class from Java I get this exception:

```
java.lang.UnsatisfiedLinkError: No implementation found for long com.example.myapp.TestHelloClass.init() (tried Java_com_example_myapp_TestHelloClass_init and Java_com_example_myapp_TestHelloClass_init__)
```

Can't see any `Java_*` methods:
```
$ android-ndk-r20/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android-objdump -t /path/to/src/main/jniLibs/x86/libmyapp.so  | grep -i java
0
```

But it *has* correctly generated all of the java classes - they get found and compiled into my app just fine.

Here's the relevant parts of my code, am I missing something? I've tried both the released 0.4 version on crates.io and master branch from here.

```
// src/java_glue.rs.in
use crate::android_c_headers::*;

use jni_sys::*;

foreign_callback!(callback HelloObserver {
  self_type HelloObserver;
  helloReceived = HelloObserver::hello_received(&self, item: &str);
});

foreign_class!(class TestHelloClass {
  self_type TestHelloClass;
  constructor TestHelloClass::new() -> TestHelloClass;

  fn hello(cb: Box<HelloObserver>) {
    cb.hello_received("blahahaha");
  }
});
```

```
// src/lib.rs
trait HelloObserver {
  fn hello_received(&self, item: &str);
}

pub struct TestHelloClass {}

impl TestHelloClass {
	pub fn new() -> TestHelloClass {
		TestHelloClass{}
	}
}

#[no_mangle]
pub extern "C" fn dummy() {
  println!("dummy");
}
```

**Comment by Dushistov** [comment]
@arrtchiu 

> src/lib.rs
> src/java_glue.rs.in
> But it has correctly generated all of the java classes 

So you should have proper `build.rs` file,
what about `src/java_glue.rs` file,  have you added it to the project?

**Comment by arrtchiu** [comment]
Thank you! I did have `src/java_glue.rs` present, identical to your example, but inside `src/lib.rs` I was missing `mod java_glue;` at the top... Adding that led to different compile-time errors and I was able to eventually get it working.
