### ISSUE TITLE
Is it possible to throw a Java Exception from the rust code?

### ISSUE THREAD

**Issue by JoyceBabu** [Dushistov/rust_swig#268]
What is the recommended method for error handling? Is it possible to throw java exceptions from the rust code?

**Comment by Dushistov** [comment]
> What is the recommended method for error handling?

returning `std::result::Result<SomeThing, String>` or `std::result::Result<SomeThing, &str>`,
this code will be automatically converted to code that return Java analog of "SomeThing" or throw error, for example you can look at https://github.com/Dushistov/rust_swig/blob/84846c680c84981188025ac641dfa30e4002bd1d/jni_tests/src/java_glue.rs.in#L156

```Rust
fn r_test_u8(v: u8) -> Result<u8, &'static str>
```
will be converted to

```Java
public static native short r_test_u8(short v) throws Exception;
```

**Comment by JoyceBabu** [comment]
Thank you
