### ISSUE TITLE
uintptr_t size mismatches

### ISSUE THREAD

**Issue by arrtchiu** [Dushistov/rust_swig#269]
When switching between 64-bit and 32-bit builds I see diffs like these in the cpp headers:

```diff
-static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 8,
+static_assert(sizeof(uintptr_t) == sizeof(uint8_t) * 4,
```

Is it worth assuming `sizeof(uintptr_t)` is always a suitable size to avoid it?

**Comment by Dushistov** [comment]
> Is it worth assuming sizeof(uintptr_t) is always a suitable size to avoid it?

I can not find any prove for this in C++ standard. 

> uintptr_t unsigned integer type capable of holding a pointer 

so if sizeof(uintptr_t) will be greater then machine word that would be fine from C++ standard point of view. Plus Rust have no ISO standard or something, so `std::mem::size_of::<usize>()` is also unclear thing, so to make sure that `usize` <-> `uintptr_t` is safe I added this assert.
