### ISSUE TITLE
Avoiding copies

### ISSUE THREAD

**Issue by arrtchiu** [Dushistov/rust_swig#274]
Minor issue, but say I have:

```rust
struct Foo {
  bars: Vec<Bar>,
}

struct Bar;

foreign_class!(class Bar {
  self_type Bar;
  constructor Bar::default() -> Bar;
  fn baz(&self) -> u32 { 42 }
});

foreign_class!(class Foo {
  self_type Foo;
  constructor Foo::default() -> Foo;
  fn bars(&self) -> Vec<Bar> { self.bars };
});
```

Accessed from C++ like so:
```c++
Foo f;
for (auto&& item: f.items()) {
  // NOTE: type of `item` here is `BarItemWrapper<false>&`
}
```

Here, in order to take ownership of an instance of `Bar`, I need to clone it again because the `BarItemWrapper` doesn't own the instance of the data. This means I end up copying twice - once into the `Vec`, the second time out of it.

I've tried return types of `&Vec<Bar>`, `Vec<&Bar>`, `&[Bar]` but none seem supported.

Is there a better way?

Perhaps one way might be to add a `pop` method to the the vector, transferring ownership to the caller?

**Comment by Dushistov** [comment]
> &[Bar] but none seem supported

`&[Bar]` is supported for C++ case,
this code is compiled just fine:

```Rust
#[derive(Default)]
pub struct Foo17 {
    bars: Vec<Bar17>,
}

#[derive(Default, Clone)]
pub struct Bar17;

foreign_class!(class Bar17 {
  self_type Bar17;
  constructor Bar17::default() -> Bar17;
  fn baz(&self) -> u32 { 42 }
});

foreign_class!(class Foo17 {
  self_type Foo17;
  constructor Foo17::default() -> Foo17;
  fn bars(&self) -> &[Bar17] { &this.bars }
});
```

**Comment by Dushistov** [comment]
> Here, in order to take ownership of an instance of Bar

If you want take ownership though, you don't need `&[Bar]`, the code should be like this:

```Rust
//Rust
foreign_class!(
fn bars(&self) -> Vec<Bar> { this.bars.clone() }
```
```C++
// C++
auto vec = foo.bars();
while (!vec.empty()) {
    auto my_bar = vec.remove(0);
}
```

**Comment by arrtchiu** [comment]
Thanks! Do you think it's practical to be able to do the same from Java too?

**Comment by Dushistov** [comment]
> Do you think it's practical to be able to do the same from Java too?

I think no. 

Returning references in general not supported for Java case.
Because of lifetime of object in Java  is not clear:
```Rust
//Rust
foreign_class!(class Boo {...
foreign_class!(class Foo {
   ...
   fn get_ref(&self) -> &Boo;
   ...
```

This works fine in C++ case for `&Boo` and `&[Boo]` because of it is possible in C++,
and C++ developers expect that `&Boo` may becomes invalid if `Foo` was destroyed.

But Java developers in general don't expect that object of class BooRef becomes invalid when `Foo` was destroyed. That's why I don't implement it for Java case. 

I usually wrap objects with `Arc` for Java case, and return by value.

**Comment by Dushistov** [comment]
Looks like no more to discuss so closing.

**Comment by arrtchiu** [comment]
Agreed, thanks very much!
