### ISSUE TITLE
package android.support.annotation does not exist

### ISSUE THREAD

**Issue by JoyceBabu** [Dushistov/rust_swig#275]
I am getting the following error when using AndroidX. The annotation package namespace in AndroidX is `androidx.annotation.NonNull`. Can this be configured?
```
error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
```

**Comment by Dushistov** [comment]
> Can this be configured?

Yes, look at https://docs.rs/rust_swig/0.4.0/rust_swig/struct.JavaConfig.html#method.use_null_annotation_from_package

**Comment by JoyceBabu** [comment]
Sorry for not checking the documentation first.
