### ISSUE TITLE
Comments on enum values cause C++ enums to be commented out

### ISSUE THREAD

**Issue by coltfred** [Dushistov/rust_swig#306]
If you have an enum definition like this:
```
foreign_enum!(
    /// Represents the reason a document can be viewed by the requesting user.
    enum AssociationType {
        /// User created the document
        Owner = AssociationType::Owner,
        /// User directly granted access to the document
        FromUser = AssociationType::FromUser,
        /// User granted access to the document via a group they are a member of
        FromGroup = AssociationType::FromGroup,
    }
);
```

It will create C++ code like this:

```
//Represents the reason a document can be viewed by the requesting user.
enum AssociationType {
    //User created the documentOwner = 0,
    //User directly granted access to the documentFromUser = 1,
    //User granted access to the document via a group they are a member ofFromGroup = 2

};
```

I believe this is because https://github.com/Dushistov/rust_swig/blob/master/macroslib/src/cpp/fenum.rs#L109 which puts the comment on the same line. Since the comments don't have an ending, this comments out the entry.

**Comment by coltfred** [comment]
If you have a preferred way you want this fixed I can PR it. Just wanted to get you to weigh in.

**Comment by Dushistov** [comment]
> If you have a preferred way you want this fixed I can PR it

No preferred way, just test + fix. So I will gladly accept PR.
