### ISSUE TITLE
JNI_OnLoad gets null JavaVM*  on older 32 bit android devices

### ISSUE THREAD

**Issue by jellelicht** [Dushistov/rust_swig#312]
In my own project, I kept running into `SIGABRT` when loading the native library. I nailed this down to the JavaVM pointer being `null` in `JNI_OnLoad`. 

This also applies to the  included android example project (which had a different problem that I made a PR for).

This only happens on Android versions before 7

**Comment by jellelicht** [comment]
Nevermind, I did not take into account a linenumber offset.

**Comment by tasn** [comment]
Have you ever figured out why it was crashing for you? Is it because of #314? Because my code doesn't use any Optional (exactly because of old Android support), but it's still crashing...
