### ISSUE TITLE
Possibly move jni headers into a shared crate?

### ISSUE THREAD

**Issue by daboross** [Dushistov/rust_swig#9]
Hi!

I'm really liking the library so far, `rust_swig` has been working quite well.

There was one thing I was wondering about though, and that's the possibility of having the `jni_c_header` types and `SwigInto` / `SwigFrom` shared between multiple crates which use `rust_swig`.

Right now if I want to split up bindings into multiple crates that depend on eachother, there will be duplicated code and/or incompatibilities depending on what I'm doing.

Would it be reasonable to instead have all "shared" things into a `swig` or `swig_types` crate that would be depended upon by projects using `rust_swig`?

It would have to be a separate crate from the crate providing swig macros, but this is a convention that's done by many other crates, such as `serde` for shared serialization/deserialization types, and the `serde_derive` for a compiler plugin for automatically implementing those types.

If it's possible, I'd also think having `jni_c_headers` as part of a separate crate would reduce the complexity of the build script, and of project setup - it would remove the need for every project using `rust_swig` to declare a `mod jni_c_headers` containing the exact same boilerplate.

On the other hand, I'm also very new to using `rust_swig`, so there might be reasons why this isn't feasible, or not useful at all. If you have the time to elaborate, I would definitely like to hear what you think about this.

Thank you for making the project, I hope you find this useful.

**Comment by Dushistov** [comment]
@daboross 

Thanks for suggestion. In fact, I thought about similar things long time ago.

1. About `jni_c_headers`.
    The problem that I did not use something like [rust-jni-sys](https://github.com/sfackler/rust-jni-sys) is Android. Android [ndk](https://en.wikipedia.org/wiki/Android_software_development#Android_NDK) uses types from `jni.h` everywhere in it's API, so if you use something like [rust-jni-sys](https://github.com/sfackler/rust-jni-sys) you can, for example get two `JNIEnv` structures, one from `jni-sys` crate another from `android-sys` crate, and they are different types.
   Thus at this point far more simple to generate via [bindgen](https://github.com/rust-lang-nursery/rust-bindgen/) from `jni.h` suitable code.
   Plus of course Android `jni.h` different from Oracle `jni.h` I am not sure is they ABI compatible, so `bindgen` is more robust solution IMHO.
  From rust_swig point of view to simplify things I can provide option in `rust_swig::Generator` to generate code that uses types like this `::user_supplied_value::jlong`,
  so you can use any crate for `jni.h` wraper? 

2. About `SwigInto / SwigFrom`
   Clearly here we depend on imaginary `jni.h` crate, and the problem with android headers in **(1)** here.
   But it is not all, `SwigInto / SwigFrom / Deref` and after I will solve #3 some special macro
   are actually some subset of rust that used to build type conversation chains for rust<->java.
   For example to create rust `&str` from java `String`, you need some like this:
```rust
let arg: jstring = ...;
let arg = JavaString::new(arg, env);//so we call Drop::drop at the end of function
let arg: &str = arg.to_str();
```
   To create these type conversation chains I used rust annotations. And somebody have to parse them to create type conversation code. So this imagenery crate with  `SwigInto / SwigFrom / Deref / macros / custom struct / custom functions` should also provide some kind of instructions to how apply this stuff to get from type A type B. Not sure how possible to implement this with current state of `cargo`.

**Comment by Dushistov** [comment]
@daboross 

Interestingly, what is your usage pattern for rust<->java,
you build several `.dll/.so` libraries for one java application, or for several java applications?

**Comment by daboross** [comment]
Sorry I haven't replied uttil now!

My ideal use case for this would be multiple rust libraries which declare different structs, and then also the Java side of those structs as well. All the rust libraries (and one binary-library depending on them) would be compiled into a single DLL, and be used by a single Java app.

From what I can tell this is pretty far from what rust_swig is aimed towards right now, so it might be best if I just try and find another solution to this. I could try to merge my crates together, but having them separated so far has been nice for organization.

Ideally I'd be exporting functionality in each library crate which could be used in rust, then with a feature flag to enable Java symbols and enable using the functionality through Java. Then an end user would have a combined crate which does little more than depend on what's needed, and provide entry points to get the rust structs and wrap them in the Java versions already ready. If this is too far fetched though, I'll probably just end up with a Rust-only interface or rewriting the code for the Java side. A lot of this would be transferring many different plain-data structs between languages too, so the inefficiency there would also probably make it not worth it.

In any case, thank you for taking the time to reply! I'm definitely coming at this without a lot of knowledge, so I'll take some time to rethink and absorbe what you've said more. The project I'm using this for is still a bit nebulous so changing things to make more sense is good.

**Comment by Dushistov** [comment]
@daboross 

>My ideal use case for this would be multiple rust libraries which declare different structs, and then also the Java side of those structs as well. All the rust libraries (and one binary-library depending on them) would be compiled into a single DLL, and be used by a single Java app.

>From what I can tell this is pretty far from what rust_swig is aimed towards right now, so it might be best if I just try and find another solution to this. I could try to merge my crates together, but having them separated so far has been nice for organization.


To sync our points of view I describe my usage scenario.

I have normal `Rust` workspace with many, many crates.
Only one of them compiled into ".so/.dll" library (`crate-type = ["cdylib"]`).
And it contains bunch of `foreign_class!` definitions describing it's own struct/trait/function and also all other crates struct/trait/function.

Why so?

Because of `Java` and `Rust` have very different semantics.
For example on `Java` you can write `objectA.setFoo(objectB.getFoo());`,
on Rust if `getFoo` gives reference and `setFoo` accept reference and
save it somewhere, then depend on lifetime such code may compiles or not.

So to create robust and clean Java API for your Rust code,
you should have all classes in one place. Return to my example,
if `objectB` from one crate and `objectA` from another, then
probably you need construction like `self_type structB;  constructor create_boo() -> Rc<RefCell<structB>>;` to create clean Java API.

You some kind of fortress between two different semantics,
and from my point of view it would be to hard to support code,
that contains bunch of crates which one expose Java/JNI interface,
it is like fortress with  hundreds of gates.

**Comment by Dushistov** [comment]
@daboross 

After some thinking (I never tought about such use case). 
You can configure `rust_swig` to generate java code into some common directory,
after that you need some `rust_swig` hacking and force it to use `Arc<Mutex<T>>` in all cases,
then I suppose your use case possible.

**Comment by daboross** [comment]
@Dushistov Thank you for the help, I'll see if I can get it to work. The one main thing I was wondering about was having `crate_a` define a bunch of rust structs with Java counterparts, and then methods from `crate_b`/`crate_c` be able to return those rust structs - and then have the Java wrapper auto-transform the `crate_a::*` structs into Java equivalents, like what's done for `String`.

For the crates I was thinking of, it might end up being better to just re-implement the functionality in Java. I'll keep experimenting with rust_swig and such, it would be nice to have this kind of thing working for future stuff - but since there isn't currently a _need_ for this, it probably wouldn't be worth putting much effort into.

In any case, thank you for all the help!
